App\Entity\AccessToken:
    type: entity
    table: access_tokens
    repositoryClass: App\Repository\ORM\AccessTokenRepository
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        token:
            type: string
            length: 20
            unique: true
            nullable: false
            column: token
        permission:
            type: integer
            nullable: false
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        deletedAt:
            type: datetime
            nullable: true
            column: deleted_at
        name:
            type: string
            length: 50
            nullable: true
    manyToOne:
        user:
            targetEntity: App\Entity\Usuario
            fetch: EAGER
            joinColumns:
                user_id:
                    referencedColumnName: id