App\Entity\AtendimentoHistorico:
    type: entity
    table: historico_atendimentos
    oneToMany:
        codificados:
            targetEntity: App\Entity\AtendimentoCodificadoHistorico
            cascade: {  }
            fetch: LAZY
            mappedBy: atendimento
            inversedBy: null
            orphanRemoval: false
            orderBy: null
