App\Entity\AtendimentoCodificadoHistorico:
    type: entity
    table: historico_atendimentos_codificados
    id:
        atendimento:
            associationKey: true
    manyToOne:
        atendimento:
            targetEntity: App\Entity\AtendimentoHistorico
            cascade: {  }
            fetch: LAZY
            inversedBy: codificados
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
