App\Entity\Departamento:
    type: entity
    table: departamentos
    repositoryClass: App\Repository\ORM\DepartamentoRepository
    id:
        id:
            type: uuid_binary
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    fields:
        nome:
            type: string
            length: 64
            unique: false
            nullable: false
        descricao:
            type: string
            length: 250
            unique: false
            nullable: false
        ativo:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            column: created_at
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
    entityListeners:
        App\Listener\ORM\DepartamentoListener: ~
