App\Entity\Lotacao:
    type: entity
    table: lotacoes
    repositoryClass: App\Repository\ORM\LotacaoRepository
    uniqueConstraints:
        lotacao_usuario_unidade_idx:
          columns: [ usuario_id, unidade_id ]
    id:
        id:
            type: uuid_binary
            generator:
                strategy: CUSTOM
            customIdGenerator:
                class: Ramsey\Uuid\Doctrine\UuidGenerator
    manyToOne:
        usuario:
            targetEntity: App\Entity\Usuario
            cascade: {  }
            fetch: LAZY
            inversedBy: lotacoes
            joinColumns:
                usuario_id:
                    referencedColumnName: id
        unidade:
            targetEntity: App\Entity\Unidade
            cascade: {  }
            fetch: LAZY
            joinColumns:
                unidade_id:
                    referencedColumnName: id
        perfil:
            targetEntity: App\Entity\Perfil
            cascade: {  }
            fetch: LAZY
            joinColumns:
                perfil_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
