App\Entity\ViewAtendimentoCodificado:
    type: entity
    table: view_atendimentos_codificados
    readOnly: true
    id:
        atendimento:
            associationKey: true
    manyToOne:
        atendimento:
            targetEntity: App\Entity\ViewAtendimento
            fetch: LAZY
            inversedBy: codificados
            joinColumns:
                atendimento_id:
                    referencedColumnName: id
            orphanRemoval: false
